# Generated by Django 4.1.2 on 2023-02-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(
                default="Default", max_length=255, verbose_name="name"
            ),
        ),
    ]
